name: Auto Release Workflow
# Triggers on PR merge to PR
on:
  pull_request:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: git fetch --unshallow --tags
      - run: npm ci
      - name: auto release
        uses: ./
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
